/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-124426-g5bbc00c05d-20260510"
#endif /* AVUTIL_FFVERSION_H */
